# Basic Information 
title: Cheng Xiao
position: Ph.D. candidate
affiliation: University of South Carolina
email: cxiao@email.sc.edu

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Cheng Xiao, Cheng, Xiao, linguistics, University of South Carolina, emotional prosody, semantics, second language acquisition, psycholinguistics.
description: This is Cheng Xiao's personal website
canonical: https://chengxiaocx.github.io

# Links 
# If you don't need one of them, you may delete the corresponding line.
#google_scholar: https://scholar.google.com/
cv_link: ./assets/Xiao.pdf
github_link: https://github.com/chengxiaocx
#linkedin: https://www.linkedin.com/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/Xiao-min.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
